### ISSUE TITLE
Issue of collision but not stopping : Gazebo Simulator

### ISSUE THREAD

**Issue by Murdism** [AV-Lab/gen0_gz_sim_ros2#17]
The collision visualizer shows collision but the vehicle does not stop
- [x] Check detection and tracking
- [x] check collision detetctor
- [x] check collision visualizer
- [x] check the publisher frame rate

**Comment by Riyadh-kh** [comment]
reflected in commit [#9d3912b](https://github.com/AV-Lab/gen0_gz_sim_ros2/commit/9d3912b6db8d69b2ca3fd6aaed88b5c89311eca5)
